"""another migration

Revision ID: c54814ee04e7
Revises: 
Create Date: 2025-06-26 02:13:13.271325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54814ee04e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verifie', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token_reinitialisation', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('token_verification_email', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['token_verification_email'])
        batch_op.create_unique_constraint(None, ['token_reinitialisation'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_verification_email')
        batch_op.drop_column('token_expiration')
        batch_op.drop_column('token_reinitialisation')
        batch_op.drop_column('email_verifie')

    # ### end Alembic commands ###
